### ISSUE TITLE
How to connect tweets, login and azure data

### ISSUE THREAD

**Issue by gideonte** [xamarinhq/app-evolve#10]
Hi

I am new in Xamarin, but I like to build conference mobile app, and I found this app-evolve which I like it very much.

How can I connect tweets, login and azure data to the application?

Thanks

**Comment by nrobison** [comment]
Hello @gideonte 

Not sure if you ever got this going but in order to tie in the data you should look under XamarinEvolve.Backend. This contains the backend solution that needs to be pushed to azure. The free tier will work for this. In order to tie in twitter the backend will need Twitter Consumer Key and Twitter Consumer Secret.
