### ISSUE TITLE
No proper documentation

### ISSUE THREAD

**Issue by haroldma-zz** [xamarinhq/app-evolve#12]
Lot of the areas of the code are not properly documented which, considering it's an open source project, makes it hard to learn from without reading every single line of code. Plus a few empty classes around the project.

**Comment by bigtfromaz** [comment]
Posting this project on GitHub was a way to share the result of efforts made by Xamarin to produce an app for the Evolve 2016 conference.  It is my suspicion that it was built to a time constraint and as such, it’s not a product quality open source deployment.  With that said, those of us at the conference were extremely impressed with the level of function and usefulness produced by James using Xamarin Forms in a very short period of time.

I am grateful for the post because the sample has shown me some really interesting techniques and a really good way to organize project structure.  As a developer, I do read the source, line-by-line.  Documentation just never seems to be as accurate as the source.
zumicts, one thing about open source is that the world gets to see both the accomplishments and the opportunities.  The great thing is that if you see problems you can also be part of the solution, if you are so inclined.

Cheers,

bigtfromaz

Lot of the areas of the code are not properly documented which, considering it's an open source project, makes it hard to learn from without reading every single line of code. Plus a few empty classes around the project.

**Comment by jamesmontemagno** [comment]
If there are specific pieces that you would like documented let me know.

**Comment by eseo-dasa** [comment]
Hi,

I m looking at the project for now 3 days and I don't understand how the custom android menu is called. I saw that they create in the Droid project an xml file called nav_menu.xml that define the left menu when the burger menu is open. And they have a NavigationViewRenderer.cs that call this file.

How the NavigationViewRenderer.cs file is called to have a menu ?
Here is what I have : 

Can you explain me please 
![screen copie](https://cloud.githubusercontent.com/assets/15190162/17481337/ef35140a-5d7c-11e6-92ef-f40d431249ed.jpg)

**Comment by jamesmontemagno** [comment]
You don't actually need a navigation view like I did as the MasterDetailPage gives you the flyout... see: https://github.com/jamesmontemagno/Hanselman.Forms

It is just a custom control if you want to use the Android menu files this way:

1.) Custom Control: https://github.com/xamarinhq/app-evolve/blob/master/src/XamarinEvolve.Clients.UI/Controls/NavigationView.cs
2.) Renderer: https://github.com/xamarinhq/app-evolve/blob/master/src/XamarinEvolve.Android/Renderers/NavigationViewRenderer.cs
3.) Use it: https://github.com/xamarinhq/app-evolve/blob/master/src/XamarinEvolve.Clients.UI/Pages/Android/MenuPage.xaml

**Comment by eseo-dasa** [comment]
Thanks a lot :)
