### ISSUE TITLE
Fails to build on Android

### ISSUE THREAD

**Issue by hstevanoski** [xamarinhq/app-evolve#6]
This fails on Xamarin Test Cloud with 66/66 devices failed.
I downloaded it, loaded it with VS and I got 160+ errors when I tried to run this app on my phone.
![android](https://cloud.githubusercontent.com/assets/10324469/15100009/b179f882-1566-11e6-85a8-42e9512e9666.jpg)
![android vs](https://cloud.githubusercontent.com/assets/10324469/15100010/b17dd786-1566-11e6-9654-b15825ea62c3.jpg)

**Comment by xal1983** [comment]
I get these errors in build for the Android version:
`6>G:\Devel\Tests\app-evolve\src\XamarinEvolve.Android\Resources\Resource.designer.cs(151,132,151,158): error CS0117: 'Resource.Layout' does not contain a definition for 'zxingscanneractivitylayout'
6>G:\Devel\Tests\app-evolve\src\XamarinEvolve.Android\Resources\Resource.designer.cs(152,132,152,158): error CS0117: 'Resource.Layout' does not contain a definition for 'zxingscannerfragmentlayout'
6>G:\Devel\Tests\app-evolve\src\XamarinEvolve.Android\Resources\Resource.designer.cs(154,92,154,104): error CS0117: 'Resource.Id' does not contain a definition for 'contentFrame'
6>G:\Devel\Tests\app-evolve\src\XamarinEvolve.Android\Resources\Resource.designer.cs(155,114,155,140): error CS0117: 'Resource.Layout' does not contain a definition for 'zxingscanneractivitylayout'
6>G:\Devel\Tests\app-evolve\src\XamarinEvolve.Android\Resources\Resource.designer.cs(156,114,156,140): error CS0117: 'Resource.Layout' does not contain a definition for 'zxingscannerfragmentlayout'`

The UWP version doesn't build either because it says it can't finish restoring packages.
I don't have a MAC nearby so I couldn't try that one...

Regards,
Andrés

**Comment by jamesmontemagno** [comment]
Can you do a full clean and re-build of the project. I have had no issues at all on multiple machines.
